# Generated by Django 3.0.3 on 2020-03-08 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Captain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft_app.Champion')),
            ],
        ),
        migrations.CreateModel(
            name='DraftLobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captain_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captain_a', to='draft_app.Captain')),
                ('captain_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captain_b', to='draft_app.Captain')),
                ('chosen_map', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map', to='draft_app.Map')),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_a', to='draft_app.Team')),
                ('team_a_bans', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bans_a', to='draft_app.Champion')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_b', to='draft_app.Team')),
                ('team_b_bans', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bans_b', to='draft_app.Champion')),
            ],
        ),
    ]
