# Generated by Django 3.0.3 on 2020-03-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='role',
            field=models.CharField(default='Melee', max_length=12),
            preserve_default=False,
        ),
    ]
